name: debian build

on:
  push:
    branches:
      - '*'
      - '!master'   # excludes master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version: [bookworm, bullseye]  # Builds for Bookworm and Bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Extract Parent Version
        run: echo "PARENT_VERSION=$(echo ${{ env.BRANCH_NAME }} | grep -oP 'v\d+\.\d+')" >> $GITHUB_ENV

      - name: Build and push ${{ matrix.debian_version }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.PARENT_VERSION }}/${{ env.BRANCH_NAME }}/${{ matrix.debian_version }}/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/agensgraph:${{ env.BRANCH_NAME }}-${{ matrix.debian_version }}
